#!/bin/bash
# File expects to be located at ~/.aliases
# To add functions that should not be shared create and use ~/.aliases.local

# Aliases
#========================

# I can't spell for shit

alias sl=ls
alias mdkir=mkdir
alias soruce=source
alias souce=source
alias brwe=brew
alias compser=composer

# Just for fun

alias fucking=sudo

# Shortcuts

alias g=git
alias dl='cd ~/Downloads'
alias dt='cd ~/Desktop'
alias h=history
alias c=clear
alias co='cd ~/Code'

# Git Shortcuts

alias gpom='git push origin master'
#alias gpod='git push origin development'
#alias grom='git reset --hard origin/master'
alias gs='git status'
alias gp='git pull'
alias ga='git add'
alias gaa='git add .'
alias gc='git commit -m '
alias gl='git log'
alias glo='git log --oneline --graph --decorate --all'
# alias gdb='git branch --merged | egrep -v "(^\*|master)" | xargs git branch -d'

# Easier navigation: .., ..., ...., ....., .4, .5, ~ and -

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
alias ~='cd ~' # `cd` is probably faster to type though
alias -- -='cd -'

# Other stuff
#alias hosts='subl /etc/hosts'
alias ping='ping -c 5'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias myip="ifconfig | grep 'inet ' | grep -v 127.0.0.1 | awk '{print $2}'"

# Recursively delete `.DS_Store` files
alias cleanup_dsstore="find . -name '*.DS_Store' -type f -ls -delete"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs & the useless sleepimage to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo grm -rf $HOME/.Trash; sudo rm -rtv /private/var/log/asl/*.asl; sudo rm /private/var/vm/sleepimage"

# Show/hide hidden files in Finder
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Show/hide all desktop icons (useful when presenting)
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"

# zshrc config
alias zshrc="${EDITOR} ${$(cd -P $(dirname $0) && cd ..; pwd -P)}"
alias reload="source ~/.zshrc && echo 'Shell config reloaded from ~/.zshrc'"

# This should be the last line of the file
# Allows for local changes
# Don't make edits below this
[ -f ".aliases.local" ] && source ".aliases.local"
